### PR TITLE
Fixing bug with jsonrpc._Method caused by debugger

### PR DESCRIPTION
**Pull request by efokschaner**
Whilst debugging jsonrpclib with PyCharm I observed odd behaviour with jsonrpc.\_Method due to pycharm using the \_\_repr\_\_, \_\_str\_\_ and \_\_dir\_\_ methods in order to populate its debug information. These calls would be handled by \_\_getattr\_\_ which would modify the object, corrupting the method name chain. xmlrpclib does not have this issue because it does not make the same optimisation of mutating the existing object but returns a new object when \_\_getattr\_\_ is called (this might actually be a preferable approach to what i am proposing, so consider it as another option).

__UPDATE__:
After working with the library a bit more i think it would be preferable to revert back to the xmlrpclib approach of not mutating \_Method and returning a a new instance each time \_\_getattr\_\_ is called. Because it allows code such as this to work:

    foo_proxy = jsonrpclib.Server('http://localhost:80')
    remote_bar = foo_proxy.objects.bar
    remote_bar.baz()
    remote_bar.qux()

If we mutate the _Method then the 'qux()' call would not behave as expected.

Let me know if there are any questions or concerns.

### CODE REVIEW

**Comment by efokschaner** [comment]
@joshmarshall I noticed you're active in the last few days so wanted to necro this and get your thoughts on this issue.

Is it not worth fixing?

**Comment by joshmarshall** [comment]
Hi @efokschaner -

I think it is worth fixing. It looks like this is still the first implementation -- did you want to open a PR with the immutable _Method() approach?

**Comment by efokschaner** [comment]
@joshmarshall Thanks for the reply, I'll prepare the PR with the recommended fix.

**Comment by efokschaner** [comment]
@joshmarshall I've updated the PR with the `__gettattr__` change. I decided to keep the `__repr__`, `__str__` and `__dir__` implementations as it still provides a better experience.

**Comment by efokschaner** [comment]
@joshmarshall How does this look?

**Comment by joshmarshall** [comment]
@efokschaner 
The change looks good, thanks for making it -- however, I think it needs a test to verify the change you made (that you referenced originally -- the varying behavior based on method lookup). On that note, I've opened a pull request ([here](https://github.com/joshmarshall/jsonrpclib/pull/40)) that ties into Travis for automated testing. If you (and anyone else) wants to review that, I can merge into master. You can go ahead and merge that branch in here and update the tests, and it will run in Travis too.

Thoughts?

**Comment by efokschaner** [comment]
@joshmarshall 
Thanks, I'll take a look at your PR and then update this one with tests.

**Comment by joshmarshall** [comment]
@efokschaner Alright -- 0.1.4 is released on PyPI and in Travis. Let's make this 0.1.5. :)

**Comment by efokschaner** [comment]
@joshmarshall Test is added, let me know how it looks.

**Comment by joshmarshall** [comment]
@efokschaner Hey -- the test looks good. Sorry, I had a pip install issue with the setup.py + the automated Travis push to PyPI last week, so I had to deal with that. Will merge this fix in as 0.1.7 hopefully this weekend if that works for you.

**Comment by efokschaner** [comment]
@joshmarshall fine by me!

**Comment by efokschaner** [comment]
@joshmarshall You might prefer to merge https://github.com/joshmarshall/jsonrpclib/pull/43 first.

**Comment by efokschaner** [comment]
@joshmarshall Don't forget this one :)

**Comment by efokschaner** [comment]
@joshmarshall any eta on this merge?

**Comment by efokschaner** [comment]
@joshmarshall Just gonna bump this PR, let me know if you're too busy to deal with the merge.

**Comment by joshmarshall** [comment]
Only took me two years, but it's closed now. Thanks so much for your work
and patience!

---
Josh Marshall
(254) 498-0366

**Comment by efokschaner** [comment]
@joshmarshall Outstanding, you should see my face right now :D

**Pull request merged**
